/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Post API
 * OpenAPI spec version: 1.0.0
 */
import type { Context, Env } from 'hono';

import { NewPost } from './posts.schemas';

export type GetPostsContext<E extends Env = any> = Context<E, '/posts'>
export type PostPostsContext<E extends Env = any> = Context<E, '/posts', { in: { json: NewPost, }, out: { json: NewPost, } }>