/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Post API
 * OpenAPI spec version: 1.0.0
 */
export interface NewPost {
  content: string;
  title: string;
}

export interface Post {
  content?: string;
  id?: number;
  title?: string;
}

